chore(workflow): update helm-lint-test.yaml for improved logging 🔄
Signed-off-by: IB Akshay <akshay.iyyadurai.balasundaram@sap.com>

diff --git a/.github/workflows/helm-lint-test.yaml b/.github/workflows/helm-lint-test.yaml
--- a/.github/workflows/helm-lint-test.yaml
+++ b/.github/workflows/helm-lint-test.yaml
@@ -20,7 +20,7 @@ jobs:
 
       - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
         with:
-          python-version: '3.x'
+          python-version: "3.x"
           check-latest: true
           token: ${{ secrets.GITHUB_TOKEN }}
 
@@ -40,27 +40,28 @@ jobs:
         if: steps.chart-list-changed.outputs.changed == 'true'
         uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
 
-      - name: Install dependencies for changed charts if needed
+      - name: Install dependencies for changed plugins if needed
         if: steps.chart-list-changed.outputs.changed == 'true'
         run: |
           for chart in $(cat changed_charts.txt); do
           plugin_dir=$(dirname "$chart")
           if [[ -f "${plugin_dir}/test-dependencies.yaml" ]]; then
-              echo "Found dependencies for plugin $plugin_dir. Installing..."
+              echo "🔍 Found dependencies for plugin $plugin_dir. Installing..."
               for dep in $(yq eval '.dependencies[]' "${plugin_dir}/test-dependencies.yaml"); do
-                echo "Installing dependency: $dep"
+                echo "📦 Installing dependent plugin: $dep ⏳"
                 if [[ ! -d "$dep/charts" ]]; then
                   echo "❌ Dependency '$dep' not found (expected ./$dep/charts)" >&2
                   exit 1
                 fi
                 # helm upgrade --install "$dep" "./$dep" --wait || {
                 helm upgrade --install "$dep" "./$dep/charts" --wait || {
-                  echo "❌ Helm install failed for dependency '$dep'" >&2
+                  echo "💥 Helm install failed for dependency '$dep'" >&2
                   exit 1
                 }
               done
+          else
+              echo "ℹ️ No test-dependencies.yaml found for plugin '$plugin_dir'. Skipping..."
           fi
-            echo "the plugin dir is $plugin_dir"
           done
 
       - name: Run chart integration tests
